version: "3.10"
services:
  worker:
    build: .
    environment:
      API_ID: $API_ID
      API_HASH: $API_HASH
      BOT_TOKEN: $BOT_TOKEN
      MONGO_URL: $MONGO_URL
      LOG_GROUP: $LOG_GROUP
      PACK_NAME: $PACK_NAME
      ALIVE_PIC: $ALIVE_PIC
      OWNER_ID: $OWNER_ID
      STRING_SESSION1: $STRING_SESSION1
